<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="" host="DESKTOP-2RSL5HK"><DocLocation><![CDATA[C:\Users\13250\Desktop\系统测试]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[系统测试]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:42]]></Time>
<TimeTick>1640149602</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1611, 11]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:42]]></Time>
<TimeTick>1640149602</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[765, 194]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:44]]></Time>
<TimeTick>1640149604</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["31901211"]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:47]]></Time>
<TimeTick>1640149607</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[723, 262]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:50]]></Time>
<TimeTick>1640149610</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:52]]></Time>
<TimeTick>1640149612</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[688, 419]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:55]]></Time>
<TimeTick>1640149615</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[968, 315]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:57]]></Time>
<TimeTick>1640149617</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[963, 299]]></Details>
<Time><![CDATA[2021/12/22 - 13:06:59]]></Time>
<TimeTick>1640149619</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1078, 292]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:01]]></Time>
<TimeTick>1640149621</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1491, 539]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:03]]></Time>
<TimeTick>1640149623</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1156, 524]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:06]]></Time>
<TimeTick>1640149626</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1494, 609]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:08]]></Time>
<TimeTick>1640149628</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1159, 522]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:10]]></Time>
<TimeTick>1640149630</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1498, 669]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:12]]></Time>
<TimeTick>1640149632</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[691, 570]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:14]]></Time>
<TimeTick>1640149634</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["sdfgsdfg"]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:16]]></Time>
<TimeTick>1640149636</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[773, 615]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:19]]></Time>
<TimeTick>1640149639</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["12345"]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:22]]></Time>
<TimeTick>1640149642</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[584, 735]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:25]]></Time>
<TimeTick>1640149645</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[592, 761]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:27]]></Time>
<TimeTick>1640149647</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[589, 790]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:29]]></Time>
<TimeTick>1640149649</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1186, 78]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:31]]></Time>
<TimeTick>1640149651</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[692, 756]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:33]]></Time>
<TimeTick>1640149653</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1487, 742]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:35]]></Time>
<TimeTick>1640149655</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1153, 527]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:37]]></Time>
<TimeTick>1640149657</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="58" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1494, 798]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:40]]></Time>
<TimeTick>1640149660</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="60" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1154, 524]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:42]]></Time>
<TimeTick>1640149662</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="62" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[742, 17]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:44]]></Time>
<TimeTick>1640149664</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[648, 340]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:46]]></Time>
<TimeTick>1640149666</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="66" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["q123"]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:48]]></Time>
<TimeTick>1640149668</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="68" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[655, 419]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:51]]></Time>
<TimeTick>1640149671</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="70" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["1232134"]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:53]]></Time>
<TimeTick>1640149673</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="72" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[664, 519]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:56]]></Time>
<TimeTick>1640149676</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="74" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["qweqwe"]]></Details>
<Time><![CDATA[2021/12/22 - 13:07:58]]></Time>
<TimeTick>1640149678</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="76" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[634, 691]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:01]]></Time>
<TimeTick>1640149681</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="78" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1178, 74]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:03]]></Time>
<TimeTick>1640149683</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="80" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[942, 872]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:06]]></Time>
<TimeTick>1640149686</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="82" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[888, 17]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:08]]></Time>
<TimeTick>1640149688</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="84" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[647, 341]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:10]]></Time>
<TimeTick>1640149690</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="86" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["qwe"]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:12]]></Time>
<TimeTick>1640149692</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="88" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[660, 447]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:15]]></Time>
<TimeTick>1640149695</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="90" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["qwe"]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:17]]></Time>
<TimeTick>1640149697</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="92" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[644, 611]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:20]]></Time>
<TimeTick>1640149700</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="94" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1182, 83]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:22]]></Time>
<TimeTick>1640149702</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="96" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1028, 12]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:24]]></Time>
<TimeTick>1640149704</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="98" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[997, 869]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:27]]></Time>
<TimeTick>1640149707</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="100" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1508, 11]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:29]]></Time>
<TimeTick>1640149709</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="102" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1637, 20]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:31]]></Time>
<TimeTick>1640149711</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="104" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1583, 80]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:33]]></Time>
<TimeTick>1640149713</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="106" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[460, 248]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:35]]></Time>
<TimeTick>1640149715</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="108" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[570, 255]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:37]]></Time>
<TimeTick>1640149717</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="110" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[710, 245]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:39]]></Time>
<TimeTick>1640149719</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[838, 255]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:42]]></Time>
<TimeTick>1640149722</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="114" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[961, 254]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:44]]></Time>
<TimeTick>1640149724</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="116" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1069, 250]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:46]]></Time>
<TimeTick>1640149726</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="118" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1199, 250]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:48]]></Time>
<TimeTick>1640149728</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="120" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1291, 247]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:50]]></Time>
<TimeTick>1640149730</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="122" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1222, 441]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:52]]></Time>
<TimeTick>1640149732</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="124" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1189, 76]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:55]]></Time>
<TimeTick>1640149735</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="126" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[659, 10]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:57]]></Time>
<TimeTick>1640149737</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="128" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1183, 79]]></Details>
<Time><![CDATA[2021/12/22 - 13:08:59]]></Time>
<TimeTick>1640149739</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="130" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[107, 170]]></Details>
<Time><![CDATA[2021/12/22 - 13:09:01]]></Time>
<TimeTick>1640149741</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="132" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[111, 247]]></Details>
<Time><![CDATA[2021/12/22 - 13:09:03]]></Time>
<TimeTick>1640149743</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="134" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1784, 273]]></Details>
<Time><![CDATA[2021/12/22 - 13:09:05]]></Time>
<TimeTick>1640149745</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="136" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1817, 369]]></Details>
<Time><![CDATA[2021/12/22 - 13:09:07]]></Time>
<TimeTick>1640149747</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="138" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[82, 115]]></Details>