<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="" host="DESKTOP-2RSL5HK"><DocLocation><![CDATA[C:\Users\13250\Documents\GitHub\G11ZUCC\系统测试\SystemTest]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SystemTest]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[登录]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:22]]></Time>
<TimeTick>1640748322</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1591, 15]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:22]]></Time>
<TimeTick>1640748322</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1591, 15]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:24]]></Time>
<TimeTick>1640748324</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[694, 198]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:25]]></Time>
<TimeTick>1640748325</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["31901211"]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:26]]></Time>
<TimeTick>1640748326</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[706, 271]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:28]]></Time>
<TimeTick>1640748328</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="18" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[706, 271]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:30]]></Time>
<TimeTick>1640748330</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["123456"]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:31]]></Time>
<TimeTick>1640748331</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[683, 432]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:33]]></Time>
<TimeTick>1640748333</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[683, 432]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:34]]></Time>
<TimeTick>1640748334</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="登录" SourceLine="-1" >
<Disp><![CDATA[Google Chrome]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2021/12/29 - 11:25:22" eTime="2021/12/29 - 11:25:36" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[登录 概要]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[表白墙基本操作]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:36]]></Time>
<TimeTick>1640748336</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[955, 313]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:36]]></Time>
<TimeTick>1640748336</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[955, 313]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:37]]></Time>
<TimeTick>1640748337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="33" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1029, 856]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:39]]></Time>
<TimeTick>1640748339</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1029, 856]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:40]]></Time>
<TimeTick>1640748340</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="37" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1041, 862]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:41]]></Time>
<TimeTick>1640748341</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="39" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1041, 862]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:42]]></Time>
<TimeTick>1640748342</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1041, 862]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:44]]></Time>
<TimeTick>1640748344</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="43" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[957, 250]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:46]]></Time>
<TimeTick>1640748346</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="45" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[957, 250]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:47]]></Time>
<TimeTick>1640748347</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1079, 242]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:48]]></Time>
<TimeTick>1640748348</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1079, 242]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:49]]></Time>
<TimeTick>1640748349</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[683, 851]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:51]]></Time>
<TimeTick>1640748351</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1490, 672]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:52]]></Time>
<TimeTick>1640748352</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1490, 672]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:53]]></Time>
<TimeTick>1640748353</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="57" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1160, 527]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:55]]></Time>
<TimeTick>1640748355</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="59" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1160, 527]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:56]]></Time>
<TimeTick>1640748356</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1494, 724]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:57]]></Time>
<TimeTick>1640748357</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="63" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1494, 724]]></Details>
<Time><![CDATA[2021/12/29 - 11:25:58]]></Time>
<TimeTick>1640748358</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="65" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1495, 771]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:00]]></Time>
<TimeTick>1640748360</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="67" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1495, 771]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:01]]></Time>
<TimeTick>1640748361</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[633, 566]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:03]]></Time>
<TimeTick>1640748363</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="71" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[636, 636]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:04]]></Time>
<TimeTick>1640748364</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="73" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["woainiwlx"]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:05]]></Time>
<TimeTick>1640748365</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="75" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[600, 757]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:07]]></Time>
<TimeTick>1640748367</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="77" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[600, 757]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:08]]></Time>
<TimeTick>1640748368</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="79" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1184, 74]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:09]]></Time>
<TimeTick>1640748369</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="81" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1184, 74]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:11]]></Time>
<TimeTick>1640748371</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="83" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[711, 753]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:12]]></Time>
<TimeTick>1640748372</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="85" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1492, 773]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:13]]></Time>
<TimeTick>1640748373</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="87" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1492, 773]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:14]]></Time>
<TimeTick>1640748374</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="89" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[698, 750]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:16]]></Time>
<TimeTick>1640748376</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="91" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1494, 822]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:17]]></Time>
<TimeTick>1640748377</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="93" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1484, 824]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:18]]></Time>
<TimeTick>1640748378</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="95" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1163, 525]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:19]]></Time>
<TimeTick>1640748379</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="97" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1163, 525]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:20]]></Time>
<TimeTick>1640748380</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1493, 870]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:22]]></Time>
<TimeTick>1640748382</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="101" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1496, 871]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:23]]></Time>
<TimeTick>1640748383</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="103" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="30" Source="表白墙基本操作" SourceLine="-1" >
<Disp><![CDATA[Google Chrome]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2021/12/29 - 11:25:36" eTime="2021/12/29 - 11:26:24" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="28" >
<Disp><![CDATA[表白墙基本操作 概要]]></Disp>
</NodeArgs>
</Action>
<Action rID="T54">
<AName><![CDATA[发布表白墙]]></AName>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:24]]></Time>
<TimeTick>1640748384</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[765, 11]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:24]]></Time>
<TimeTick>1640748384</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="108" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[765, 11]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:25]]></Time>
<TimeTick>1640748385</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="110" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[759, 354]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:27]]></Time>
<TimeTick>1640748387</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[757, 353]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:28]]></Time>
<TimeTick>1640748388</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="114" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["zuanzuan"]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:29]]></Time>
<TimeTick>1640748389</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="116" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[709, 425]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:31]]></Time>
<TimeTick>1640748391</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="118" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[709, 425]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:32]]></Time>
<TimeTick>1640748392</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="120" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["iloveyou"]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:34]]></Time>
<TimeTick>1640748394</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="122" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[698, 563]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:36]]></Time>
<TimeTick>1640748396</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="124" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[698, 563]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:37]]></Time>
<TimeTick>1640748397</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="126" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["woaini xiaozuanzuan mua"]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:38]]></Time>
<TimeTick>1640748398</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="128" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[698, 563]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:41]]></Time>
<TimeTick>1640748401</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="130" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[636, 695]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:42]]></Time>
<TimeTick>1640748402</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="132" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[636, 695]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:43]]></Time>
<TimeTick>1640748403</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="134" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1176, 71]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:45]]></Time>
<TimeTick>1640748405</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="136" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1176, 71]]></Details>
<Time><![CDATA[2021/12/29 - 11:26:46]]></Time>
<TimeTick>1640748406</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="138" Source="发布表白墙" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>