<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="中国标准时间">
<General productName="HP Unified Functional Testing" productVer="11.50" os="" host="LAPTOP-0JH0O2IK"><DocLocation><![CDATA[C:\Users\lenovo\Documents\Unified Functional Testing\注册]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[注册]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" ShowDifference="False">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Google Chrome]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:57]]></Time>
<TimeTick>1640144337</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[696, 192]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:57]]></Time>
<TimeTick>1640144337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[696, 192]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:57]]></Time>
<TimeTick>1640144337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[694, 257]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:57]]></Time>
<TimeTick>1640144337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[694, 257]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:57]]></Time>
<TimeTick>1640144337</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:58]]></Time>
<TimeTick>1640144338</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicBack&gt"]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:59]]></Time>
<TimeTick>1640144339</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["31901208"]]></Details>
<Time><![CDATA[2021/12/22 - 11:38:59]]></Time>
<TimeTick>1640144339</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="22" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[700, 337]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:00]]></Time>
<TimeTick>1640144340</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[700, 337]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:00]]></Time>
<TimeTick>1640144340</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["31901208"]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:01]]></Time>
<TimeTick>1640144341</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="28" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[695, 419]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:02]]></Time>
<TimeTick>1640144342</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[695, 419]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:02]]></Time>
<TimeTick>1640144342</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["31901208"]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:03]]></Time>
<TimeTick>1640144343</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[649, 499]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:04]]></Time>
<TimeTick>1640144344</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[649, 499]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:04]]></Time>
<TimeTick>1640144344</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[669, 626]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:04]]></Time>
<TimeTick>1640144344</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[669, 626]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:05]]></Time>
<TimeTick>1640144345</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[691, 587]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:05]]></Time>
<TimeTick>1640144345</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.DblClick]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[691, 587]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:05]]></Time>
<TimeTick>1640144345</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Google Chrome.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["554547"]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:06]]></Time>
<TimeTick>1640144346</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="48" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[713, 586]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:07]]></Time>
<TimeTick>1640144347</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[681, 701]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:07]]></Time>
<TimeTick>1640144347</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[681, 701]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:07]]></Time>
<TimeTick>1640144347</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="54" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Chrome Legacy Window.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[681, 701]]></Details>
<Time><![CDATA[2021/12/22 - 11:39:08]]></Time>
<TimeTick>1640144348</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Chrome Legacy Window.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Google Chrome]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="2021/12/22 - 11:38:56" eTime="2021/12/22 - 11:39:08" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Action1 概要]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[注册 迭代 1 (行 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="2021/12/22 - 11:38:56" eTime="2021/12/22 - 11:39:08" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[测试 注册 概要]]></Disp>
</NodeArgs>
</Doc>
</Report>